### ISSUE TITLE
Please don't modify anything outside the config directory without at least warning the user what will be modified and giving us an abort function.

### ISSUE THREAD

**Issue by dwLG00** [richardfeynmanrocks/.emacs.d#1]
This is extremely unprofessional and you should go to open source jail. You should also be kept at least 100 feet from  configs of any type and use Notepad for all of your programming and note-taking needs from now on.

**Comment by quantumish** [comment]
#wontfix

**Comment by quantumish** [comment]
In all seriousness, reopening because this is an actual problem if I intend to share this config with people

**Comment by quantumish** [comment]
Alright, 965aa0db9d95ccded823a5efa4191fef30a01b9f should partially address this — automatic system configuration has to be manually enabled now. I have yet to include a disclaimer on what it actually modifies.

**Comment by quantumish** [comment]
Also a TODO: manual enabling of automatic package installation? Also toggling of what is configured as mentioned in the original issue?
